title: Barry Ryan WebPage
description: I am PhD Candidate at the University of Edinburgh on the Biomedical Artificial Intelligence CDT Programme. My research seeks to integrate biological datasets using network taxonomies and to perform insightful classifications in heterogenous diseases using graph neural networks.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
